version: '3'

services:

  1.32-ubuntu18:
    build:
      context: ./ubuntu-18
      dockerfile: ../Dockerfile
      args:
        BUILDER_VERSION: ubuntu18
        RUST_VERSION: '1.32.0'
    image: odaceo/rust:1.32-ubuntu18
